### ISSUE TITLE
AssignQuests

### ISSUE THREAD

**Issue by rbendary94** [maibelbesy/QuestBoard#18]
A User can now assign another User to a quest successfully.

**Comment by Mbehairy** [comment]
When you assign a task to someone who doesn't exist, the app fails and gives an error "undefined method `id' for nil:NilClass"

**Comment by Mbehairy** [comment]
When someone rejects the Quest. It still appears on the assigners board, but when you click on it the app fails and returns an error 'Couldn't find UsersQuest with 'id''
